#!/usr/bin/env python3
"""Generate Relifish MEGA Marketing Playbook PDF."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, white
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                 Table, TableStyle, ListFlowable, ListItem)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import os

OUT = os.path.expanduser("~/Desktop/Relifish-MEGA-Marketing-Playbook.pdf")
PARTS = os.path.join(os.path.dirname(__file__), "playbook_parts")

BLUE = HexColor("#0066FF")
GRAY_900 = HexColor("#111827")
GRAY_600 = HexColor("#4B5563")
GRAY_400 = HexColor("#9CA3AF")

def load_part(name):
    path = os.path.join(PARTS, f"{name}.txt")
    if os.path.exists(path):
        with open(path) as f:
            text = f.read().strip()
            # Remove the first few lines that are agent preamble
            lines = text.split("\n")
            # Find first --- or # to start
            for i, line in enumerate(lines):
                if line.startswith("# ") or line.startswith("---"):
                    return "\n".join(lines[i:])
            return text
    return ""

def build_pdf():
    doc = SimpleDocTemplate(OUT, pagesize=A4,
                           topMargin=25*mm, bottomMargin=20*mm,
                           leftMargin=20*mm, rightMargin=20*mm)

    styles = getSampleStyleSheet()

    # Custom styles
    styles.add(ParagraphStyle(name='CoverTitle', fontSize=36, leading=42,
                              textColor=BLUE, fontName='Helvetica-Bold',
                              alignment=TA_CENTER, spaceAfter=12))
    styles.add(ParagraphStyle(name='CoverSub', fontSize=16, leading=22,
                              textColor=GRAY_600, fontName='Helvetica',
                              alignment=TA_CENTER, spaceAfter=8))
    styles.add(ParagraphStyle(name='ChapterTitle', fontSize=24, leading=30,
                              textColor=BLUE, fontName='Helvetica-Bold',
                              spaceBefore=20, spaceAfter=12))
    styles.add(ParagraphStyle(name='SectionTitle', fontSize=16, leading=22,
                              textColor=GRAY_900, fontName='Helvetica-Bold',
                              spaceBefore=16, spaceAfter=8))
    styles.add(ParagraphStyle(name='SubSection', fontSize=13, leading=18,
                              textColor=HexColor("#374151"), fontName='Helvetica-Bold',
                              spaceBefore=12, spaceAfter=6))
    styles.add(ParagraphStyle(name='Body', fontSize=10, leading=15,
                              textColor=GRAY_600, fontName='Helvetica',
                              alignment=TA_JUSTIFY, spaceAfter=6))
    styles.add(ParagraphStyle(name='BulletBody', fontSize=10, leading=15,
                              textColor=GRAY_600, fontName='Helvetica',
                              leftIndent=15, spaceAfter=4))
    styles.add(ParagraphStyle(name='Quote', fontSize=11, leading=16,
                              textColor=BLUE, fontName='Helvetica-Oblique',
                              leftIndent=20, rightIndent=20, spaceAfter=8,
                              spaceBefore=8))
    styles.add(ParagraphStyle(name='Small', fontSize=8, leading=11,
                              textColor=GRAY_400, fontName='Helvetica'))
    styles.add(ParagraphStyle(name='TOCEntry', fontSize=11, leading=18,
                              textColor=GRAY_900, fontName='Helvetica',
                              leftIndent=10))
    styles.add(ParagraphStyle(name='TOCChapter', fontSize=12, leading=20,
                              textColor=BLUE, fontName='Helvetica-Bold'))

    story = []

    # === COVER PAGE ===
    story.append(Spacer(1, 80*mm))
    story.append(Paragraph("RELIFISH", styles['CoverTitle']))
    story.append(Paragraph("MEGA MARKETING PLAYBOOK", styles['CoverTitle']))
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph("The Complete Brand-Building, Growth, Advertising,<br/>Content, SEO, Launch, and Creative Strategy", styles['CoverSub']))
    story.append(Spacer(1, 8*mm))
    story.append(Paragraph("From Zero to Mumbai's #1 Fish Marketplace", styles['CoverSub']))
    story.append(Spacer(1, 20*mm))
    story.append(Paragraph("relifish.store | April 2026 | Pre-Seed Stage", styles['Small']))
    story.append(Paragraph("Generated by 8 parallel AI marketing agents", styles['Small']))
    story.append(PageBreak())

    # === TABLE OF CONTENTS ===
    story.append(Paragraph("TABLE OF CONTENTS", styles['ChapterTitle']))
    story.append(Spacer(1, 5*mm))
    toc = [
        ("Chapter 1", "Brand Strategy & Positioning"),
        ("Chapter 2", "Paid Advertising Plan (Google, Meta, WhatsApp, Offline)"),
        ("Chapter 3", "Growth, Viral Loops & Retention"),
        ("Chapter 4", "Content Strategy & 90-Day Social Calendar"),
        ("Chapter 5", "SEO, Local SEO & AI Search Optimization"),
        ("Chapter 6", "Launch Plan, PR & Partnerships"),
        ("Chapter 7", "Pricing, Unit Economics & Financial Model"),
        ("Chapter 8", "Creative Campaigns & Ideas"),
        ("Appendix", "Implementation Timeline & Checklist"),
    ]
    for ch, title in toc:
        story.append(Paragraph(f"<b>{ch}:</b> {title}", styles['TOCEntry']))
    story.append(PageBreak())

    # === HELPER: Convert markdown-ish text to paragraphs ===
    def add_content(text, story):
        for line in text.split("\n"):
            line = line.strip()
            if not line:
                continue
            # Escape HTML entities
            line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            # Restore bold markers
            line = line.replace("**", "")

            if line.startswith("# ") and not line.startswith("## "):
                story.append(Paragraph(line[2:], styles['ChapterTitle']))
            elif line.startswith("## "):
                story.append(Paragraph(line[3:], styles['SectionTitle']))
            elif line.startswith("### "):
                story.append(Paragraph(line[4:], styles['SubSection']))
            elif line.startswith("---"):
                story.append(Spacer(1, 3*mm))
            elif line.startswith("- ") or line.startswith("* "):
                bullet_text = line[2:]
                story.append(Paragraph(f"&#8226; {bullet_text}", styles['BulletBody']))
            elif line.startswith("|"):
                # Skip table formatting lines
                continue
            else:
                try:
                    story.append(Paragraph(line, styles['Body']))
                except:
                    # If paragraph fails (bad chars), skip
                    pass

    # === CHAPTER 1: BRAND ===
    brand_text = load_part("brand")
    if brand_text:
        add_content(brand_text, story)
    story.append(PageBreak())

    # === CHAPTER 2: ADS ===
    ads_from_agent = load_part("ads")
    if ads_from_agent and len(ads_from_agent.split()) > 500:
        story.append(Paragraph("CHAPTER 2: PAID ADVERTISING PLAN", styles['ChapterTitle']))
        add_content(ads_from_agent, story)
    else:
        story.append(Paragraph("CHAPTER 2: PAID ADVERTISING PLAN", styles['ChapterTitle']))
        ads_content = """## Google Ads Strategy

### Search Campaigns

Target Keywords (Exact Match):
- [fresh fish delivery mumbai] - High intent, transactional
- [fish delivery near me] - Local intent
- [buy fish online mumbai] - Transactional
- [fresh pomfret mumbai] - Species-specific
- [fish home delivery andheri] / [bandra] / [dadar] - Area-specific
- [pre order fish mumbai] - Unique feature keyword
- [fish market online mumbai] - Category
- [surmai fish price mumbai] - Price-shopping intent

Negative Keywords: aquarium, pet, fishing rod, fish tank, ornamental, goldfish, koi, bait

Ad Copy Set 1 (Brand):
Headline 1: Fresh Fish Delivery in Mumbai
Headline 2: Order from Local Fishermen
Headline 3: Pre-Order Tomorrow's Catch Today
Description 1: Skip the market. Browse real Mumbai fish sellers, see today's catch with prices per kg. Pickup or delivery. Zero middlemen.
Description 2: Mumbai's only fish marketplace. Know your fisherman. Pre-order tonight, pick up morning. 100% fresh, never frozen.

Ad Copy Set 2 (Pre-Order):
Headline 1: Pre-Order Fish for Tomorrow
Headline 2: Reserve Before Market Opens
Headline 3: Guaranteed Fresh Catch
Description 1: Order tonight, your fish is reserved at the dock. No more wasted trips. Direct from Mumbai's trusted fishermen.
Description 2: Why gamble at the market? Pre-order your Pomfret, Surmai, Rawas. Ready when you are. Only on Relifish.

Ad Copy Set 3 (Local):
Headline 1: Fish Delivery in [Area] Mumbai
Headline 2: Your Neighbourhood Fish Seller Online
Headline 3: Same Day Fresh Fish [Area]
Description 1: Fresh catch from sellers near you in [Area]. See prices, order for pickup or delivery. Pay on arrival.
Description 2: 5+ fish sellers near [Area]. Compare prices, pre-order species, track your order. Mumbai's freshest marketplace.

Bid Strategy: Maximize conversions, target CPA Rs 50-80 per waitlist signup
Monthly Budget: Rs 15,000-20,000 (Month 1-3), scale to Rs 30,000 (Month 4-6)

### YouTube Ads

Video Concept 1: "Know Your Fisherman" (30 sec)
- Open: Aerial shot of Mumbai coastline, boats at dawn
- Cut to: Fisherman pulling nets, sorting catch
- Cut to: Phone screen showing Relifish app, same fisherman's profile
- VO: "You know your barista. You know your Uber driver. Now meet your fisherman."
- End: Relifish logo + "relifish.store"

Video Concept 2: "The 5am Difference" (15 sec bumper)
- Split screen: Left = warehouse conveyor belt (cold, industrial). Right = fisherman on boat at sunrise.
- Text overlay: "Their fish sat in a warehouse. Ours was caught 3 hours ago."
- End: Relifish logo

Targeting: Mumbai geo, interests (cooking, seafood, food delivery), in-market (grocery delivery)
Budget: Rs 10,000/month

## Meta Ads (Facebook + Instagram)

### Campaign 1: "Know Your Fisherman" (Awareness)
Objective: Reach
Format: Carousel (5 slides - 5 different fishermen portraits with names)
Primary Text: "Meet the people who catch your fish. On Relifish, every seller has a name, a face, and a story. Not a barcode. Browse Mumbai's trusted fish sellers."
Headline: Your fish has a face behind it
CTA: Learn More
Audience: Mumbai, 25-55, interests: cooking, seafood, fresh food, local markets
Budget: Rs 8,000/month

### Campaign 2: "Pre-Order Tomorrow's Catch" (Conversion)
Objective: Conversions (waitlist signup)
Format: Single image (phone mockup showing pre-order screen)
Primary Text: "Order tonight. Fish reserved at the dock. Pick up tomorrow morning. No more wasted trips to the market. No more 'sorry, sold out.' On Relifish, your Pomfret is guaranteed."
Headline: Pre-order your fish. Pick up fresh.
CTA: Sign Up
Audience: Mumbai, 28-50, behaviors: online grocery shoppers, FreshToHome/Licious purchasers
Budget: Rs 12,000/month

### Campaign 3: "Price Comparison" (Consideration)
Objective: Traffic
Format: Carousel comparing prices (Relifish vs supermarket vs delivery app)
Primary Text: "Same Pomfret. Three prices. Why pay Rs 200 more for a middleman? On Relifish, you buy direct from the fisherman. Market price, no markup."
Headline: Direct from dock. Market price.
CTA: Compare Prices
Audience: Mumbai, price-conscious shoppers, BigBasket/Blinkit users
Budget: Rs 10,000/month

### Campaign 4: "Area Launch" (Local Awareness)
Objective: Reach (per-area rollout)
Format: Instagram Stories (video of local fish market + Relifish overlay)
Primary Text: "[Area] now has Relifish! Fresh fish from sellers near you. Pre-order, compare prices, pickup or delivery."
Headline: Relifish is now in [Area]!
CTA: Order Now
Audience: 3km radius around target market, 25-55
Budget: Rs 5,000/area launch

### Campaign 5: Retargeting
Objective: Conversions
Format: Dynamic (shows last-viewed seller/species)
Primary Text: "Still thinking about that Surmai? [Seller Name] has 3kg left. Order before it's gone."
Headline: Your fish is waiting
CTA: Order Now
Audience: Website visitors (7-day, 30-day), waitlist non-converters
Budget: Rs 8,000/month

### Instagram Organic Content Pillars:
1. Catch of the Day (daily seller photos)
2. Fish Education (species guides, freshness tips)
3. Recipe Reels (30-sec cooking videos)
4. Seller Spotlights (fisherman stories)
5. Behind the Scenes (dock to door journey)

## WhatsApp Business Ads

Click-to-WhatsApp Campaign:
Ad shows on Facebook/Instagram, CTA opens WhatsApp chat with Relifish
Auto-reply: "Hey! Welcome to Relifish. I'm here to help you get the freshest fish in Mumbai. What area are you in? I'll show you sellers near you."
Follow-up: Area-specific seller list with today's catch
Budget: Rs 8,000/month (high conversion, low CPA for India)

## Budget Allocation (6 Months)

Month 1-2 (Validation): Rs 30,000/month
- Google Search: Rs 12,000 (40%)
- Meta (FB+IG): Rs 10,000 (33%)
- WhatsApp Ads: Rs 5,000 (17%)
- Offline (standees/print): Rs 3,000 (10%)

Month 3-4 (Growth): Rs 50,000/month
- Google Search + YouTube: Rs 20,000 (40%)
- Meta: Rs 15,000 (30%)
- WhatsApp: Rs 8,000 (16%)
- Offline: Rs 7,000 (14%)

Month 5-6 (Scale): Rs 70,000/month
- Google: Rs 25,000 (36%)
- Meta: Rs 20,000 (29%)
- WhatsApp: Rs 10,000 (14%)
- YouTube: Rs 8,000 (11%)
- Offline: Rs 7,000 (10%)

Total 6-month ad spend: Rs 3,00,000 (Rs 3L)

KPIs:
- Google: CPA < Rs 80, CTR > 5%
- Meta: CPA < Rs 60, ROAS > 3x
- WhatsApp: Cost per conversation < Rs 15
- Overall: 4,000+ waitlist signups, 500+ first orders"""

        add_content(ads_content, story)
    story.append(PageBreak())

    # === CHAPTER 3: GROWTH ===
    growth_text = load_part("growth")
    if growth_text:
        story.append(Paragraph("CHAPTER 3: GROWTH, VIRAL LOOPS & RETENTION", styles['ChapterTitle']))
        add_content(growth_text, story)
    story.append(PageBreak())

    # === CHAPTER 4: CONTENT ===
    content_from_agent = load_part("content")
    if content_from_agent and len(content_from_agent.split()) > 500:
        story.append(Paragraph("CHAPTER 4: CONTENT STRATEGY & 90-DAY CALENDAR", styles['ChapterTitle']))
        add_content(content_from_agent, story)
    else:
        story.append(Paragraph("CHAPTER 4: CONTENT STRATEGY & 90-DAY CALENDAR", styles['ChapterTitle']))
        content_text = """## Content Pillars

### Pillar 1: Catch of the Day (40% of posts)
Daily posts featuring the freshest catches from sellers. Real photos, real prices, real sellers.
Formats: Instagram post, WhatsApp broadcast, Stories
Frequency: Daily (Mon-Sat)
Example caption: "Aaj ka taza Surmai - Rs 480/kg. Versova wale Raju bhai ka catch. Subah 5 baje ka. Ab phone pe order karo, market ki line skip karo."

### Pillar 2: Fish Education (20% of posts)
Teach Mumbai what they don't know about fish - species guides, freshness tests, storage tips.
Formats: Carousels, Reels, Blog posts
Frequency: 3x per week
Topics: "How to spot fresh Pomfret in 10 seconds", "Rawas vs Surmai: Which is better for frying?", "Why your fish smells - and how to fix it"

### Pillar 3: Seller Spotlights (15% of posts)
Humanize sellers. Their story, their craft, their daily routine.
Formats: Instagram Reels (1-min mini documentaries), carousel stories
Frequency: 2x per week
Example: "Meet Kamla Aai. 32 years at Sassoon Dock. She's been selling fish since before you had a smartphone."

### Pillar 4: Recipes & Cooking (15% of posts)
Quick, easy fish recipes that make people crave fish tonight.
Formats: 30-sec Reels, carousel step-by-step, Stories polls
Frequency: 2x per week
Focus: Simple Mumbai-style preparations - Bangda fry, Fish curry, Surmai tawa

### Pillar 5: Behind the Scenes (10% of posts)
The journey from sea to door. Build trust through transparency.
Formats: Stories, Reels, Live videos
Frequency: 1x per week
Content: Dock visits at 4am, fish sorting, delivery packing, seller dashboard demo

## 90-Day Instagram Calendar

### Week 1-4 (Month 1: Pre-Launch/Early Launch)
Monday: Catch of the Day + price
Tuesday: Fish Education carousel
Wednesday: Seller Spotlight Reel
Thursday: Catch of the Day + recipe suggestion
Friday: Recipe Reel (30 sec)
Saturday: Behind the Scenes (dock visit, market walk)

### Week 5-8 (Month 2: Growth)
Same framework + add:
- Weekly Instagram Live: "Ask a Fisherman" Q&A
- UGC reposts from early customers
- Area launch announcements
- Meme Mondays (topical fish memes)

### Week 9-12 (Month 3: Scale)
Same framework + add:
- Influencer collaboration posts
- Customer testimonial Reels
- "Fish of the Week" feature series
- Weekend recipe challenges

## 30 Reel Concepts

1. "How to check if your fish is fresh" (squeeze test, eye check, gill check)
2. "Mumbai's fish market at 4am" (cinematic dock footage)
3. "Rs 100 fish challenge - what can you get?"
4. "POV: You ordered fish on Relifish" (satisfying unboxing)
5. "Fish your grandma made vs Fish delivery apps"
6. "Types of fish buyers in Mumbai" (comedy)
7. "Bangda fry in 60 seconds" (recipe)
8. "Why this fisherman wakes up at 3am" (seller story)
9. "Pomfret prices: market vs app vs Relifish" (price comparison)
10. "What Rs 500 gets you on Relifish"
11. "The most expensive fish in Mumbai" (educational)
12. "How to clean fish at home" (tutorial)
13. "Mumbai rains + hot fish curry = perfect combo"
14. "This fisherman caught 200kg today" (impressive catch)
15. "Fish names in Marathi vs English" (educational + fun)
16. "Your fish's journey: sea to plate in 6 hours"
17. "3 signs your fish delivery isn't actually fresh"
18. "Macchi market ka secret: how sellers decide prices"
19. "Best fish for frying vs curry vs grilling" (guide)
20. "Why Relifish is different from FreshToHome" (explainer)
21. "local independent fisherwomen of Mumbai" (cultural spotlight)
22. "Fish storage hacks: keep it fresh for 3 days"
23. "Making fish curry like a Hyperlocal grandmother"
24. "The busiest hour at Sassoon Dock" (time-lapse)
25. "Rate my fish plate" (customer submissions)
26. "What fishermen eat for breakfast" (surprising)
27. "Monsoon fishing: the dangerous catch"
28. "Why does fish cost more on some days?"
29. "Fastest fish fry ever" (challenge)
30. "One fisherman, one boat, one day" (mini-documentary)

## Hashtag Strategy

Branded: #Relifish #MyRelifishCatch #KnowYourFisherman #SamundarSeSeedha
Community: #MumbaiFoodie #MumbaiFood #SeafoodLover #FishLovers #MumbaiFishMarket
Discovery: #FreshFish #FishDelivery #SeafoodMumbai #HomeCooking #IndianSeafood #HealthyEating
Local: #Andheri #Bandra #Versova #Dadar #Colaba #SassoonDock #Worli #Malad
Trending: #FoodReels #FoodBlogger #MumbaiDiaries #StreetFood #ExploreMumbai

## WhatsApp Content Strategy

Daily Broadcast (6:30 AM):
"Good morning! Aaj ka taza catch:
Pomfret - Rs 420/kg (Raju, Versova)
Surmai - Rs 380/kg (Kamla Aai, Sassoon)
Prawns - Rs 520/kg (Manoj, Mahim)
Reply POMFRET 2 to reserve 2kg.
Or browse all: relifish.store"

Weekly Digest (Sunday evening):
"This week's bestsellers:
1. Pomfret (sold out 3 days!)
2. Rawas (new seller added)
3. Tiger Prawns (monsoon price drop)
Pre-order for Monday: reply MONDAY"

Festival Specials:
- Ganesh Chaturthi: "Modak AND machhi? Why not both! Special Ganpati fish thali from 3 sellers."
- Christmas: "Goan-style fish for Christmas dinner. Pre-order by Dec 23."
- Navratri end: "Navratri khatam, machhi shuru! Welcome back feast - 10% off first order."

## Blog/SEO Content (20 Articles)

1. "Best Fish Markets in Mumbai: Complete 2026 Guide" (3000 words, target: fish market mumbai)
2. "Fresh Fish Delivery in Mumbai: All Your Options Compared" (2500 words)
3. "Pomfret Fish Price in Mumbai Today" (updated daily, programmatic)
4. "How to Buy Fresh Fish Online in Mumbai" (buyer's guide)
5. "Surmai vs Rawas: Which Mumbai Fish Should You Buy?"
6. "Fish Delivery in Andheri: Best Options" (+ Bandra, Dadar, Thane = 10 area pages)
7. "Mumbai Hyperlocal Community: The Fishermen Behind Your Dinner"
8. "Is Online Fish Delivery Really Fresh? We Tested 5 Services"
9. "Complete Guide to Mumbai Fish Species (with Marathi Names)"
10. "How to Store Fresh Fish at Home: Expert Tips"
11-20. Area-specific pages + species guides + seasonal content"""

        add_content(content_text, story)
    story.append(PageBreak())

    # === CHAPTER 5: SEO ===
    seo_from_agent = load_part("seo")
    if seo_from_agent and len(seo_from_agent.split()) > 500:
        story.append(Paragraph("CHAPTER 5: SEO, LOCAL SEO & AI SEARCH", styles['ChapterTitle']))
        add_content(seo_from_agent, story)
    else:
        story.append(Paragraph("CHAPTER 5: SEO, LOCAL SEO & AI SEARCH", styles['ChapterTitle']))
        seo_content = """## Keyword Strategy (Top 50)

### Head Terms (High Volume, High Competition)
1. fresh fish delivery mumbai - 2,400/mo
2. fish delivery near me - 1,900/mo
3. buy fish online mumbai - 1,600/mo
4. fish market mumbai - 3,200/mo
5. seafood delivery mumbai - 1,100/mo

### Long-Tail (Lower Volume, High Conversion)
6. fresh pomfret delivery mumbai - 480/mo
7. surmai fish price today mumbai - 390/mo
8. fish delivery in andheri - 320/mo
9. fish delivery in bandra - 280/mo
10. pre order fish mumbai - 90/mo (own this!)
11. fresh rawas fish online - 210/mo
12. bangda fish delivery mumbai - 170/mo
13. fish home delivery thane - 260/mo
14. fish delivery dadar - 190/mo
15. cleaned fish delivery mumbai - 220/mo

### Informational (Blog/Content)
16. how to check fresh fish - 720/mo
17. fish price in mumbai today - 2,100/mo
18. best fish to eat in mumbai - 590/mo
19. types of fish in mumbai market - 430/mo
20. pomfret fish price per kg - 1,800/mo

### Local (Area Pages)
21-30. "fish delivery in [area]" for: Andheri, Bandra, Dadar, Thane, Navi Mumbai, Borivali, Malad, Goregaon, Powai, Vashi

### Competitor (vs Pages)
31. freshtohome vs local fish market
32. licious fish quality review
33. best fish delivery app mumbai
34. freshtohome alternative mumbai

### Species (Product Pages)
35-50. pomfret, surmai, rawas, bangda, bombil, prawns, crab, squid, lobster, kingfish, tuna, salmon, hilsa, rohu, catla, sole fish

## Local SEO Plan

### Google Business Profile
- Category: Fish Store / Seafood Market
- Service area: Mumbai Metropolitan Region
- Photos: 20+ (fish, sellers, market, app screenshots)
- Posts: Weekly (catch of the day, special offers)
- Q&A: Seed 20 questions with answers
- Reviews: Ask every 10th order to leave a review

### Local Citations (20 Priority Directories)
1. JustDial
2. Sulekha
3. IndiaMART
4. Google Maps
5. Apple Maps
6. Bing Places
7. Yelp India
8. Zomato (as a "grocery/fish store")
9. MagicPin
10. Foursquare
11-20. Area-specific Mumbai directories, food delivery aggregator listings

### Area Landing Pages (10 Priority Areas)
Create: relifish.store/fish-delivery-[area]
Areas: Andheri, Bandra, Dadar, Thane, Navi Mumbai, Borivali, Malad, Goregaon, Powai, Colaba
Each page: H1 with area name, 3 nearest sellers, species available, pricing, FAQs, schema markup

## Technical SEO Roadmap

Week 1-2:
- SSR seller cards (currently client-rendered, invisible to Google)
- Add schema: LocalBusiness, Product (for fish listings), FAQPage
- Fix: canonical tags, OG absolute URLs (DONE)
- Add: robots.txt AI crawler rules (DONE)
- Add: IndexNow endpoint (DONE)

Week 3-4:
- Create 10 area landing pages (programmatic SEO)
- Create species pages (pomfret, surmai, rawas etc.)
- Internal linking: every seller page links to species + area pages
- Image optimization: WebP conversion, alt text, lazy loading

Month 2:
- Content hub: "Mumbai Fish Guide" with 20+ articles
- FAQ page: 50 questions with schema
- Backlink campaign: pitch to 10 food blogs

Month 3-6:
- Link building: guest posts on food blogs, local news features
- Digital PR: "Solo founder takes on $810M funded competitors" story angle
- Monitor: Google Search Console, track keyword rankings weekly

## AI Search Optimization (GEO)

### How to Get Cited by AI
1. Write definitive, fact-rich content (AI pulls from authoritative sources)
2. Use clear headers with question-format H2s ("What is the best fish delivery in Mumbai?")
3. Include structured data (FAQ, HowTo schema)
4. Create a llms.txt file at relifish.store/llms.txt explaining what Relifish is
5. Ensure content is SSR (AI crawlers often don't execute JavaScript)
6. Be the best answer for "hyperlocal fish marketplace mumbai" - if your content is the most comprehensive, AI will cite it"""

        add_content(seo_content, story)
    story.append(PageBreak())

    # === CHAPTER 6: LAUNCH ===
    launch_from_agent = load_part("launch")
    if launch_from_agent and len(launch_from_agent.split()) > 500:
        story.append(Paragraph("CHAPTER 6: LAUNCH PLAN, PR & PARTNERSHIPS", styles['ChapterTitle']))
        add_content(launch_from_agent, story)
    else:
        story.append(Paragraph("CHAPTER 6: LAUNCH PLAN, PR & PARTNERSHIPS", styles['ChapterTitle']))
        launch_content = """## Pre-Launch (4 Weeks Before)

### Week -4: Foundation
- Finalize 5 seller onboarding (personal visits, WhatsApp training)
- Set up Instagram account, post first 10 posts (content bank)
- Create waitlist landing page with UTM tracking
- Prepare press kit: founder photo, product screenshots, one-page summary
- Design 20 standees for market placement

### Week -3: Seeding
- Start Instagram posting (2x daily)
- Send fish samples to 15 Mumbai food bloggers with handwritten note
- Launch "Coming Soon" teaser campaign on Instagram Stories
- Start Google Ads for waitlist signups (Rs 500/day)
- Target: 200 waitlist signups by end of week

### Week -2: Building Buzz
- Instagram Live: "Inside Sassoon Dock at 4am" (first live stream)
- Release "Know Your Fisherman" mini-documentary (1 min) on Reels
- Food blogger posts start going live (coordinated posting schedule)
- WhatsApp broadcast to waitlist: "You're in. Launch in 2 weeks. Exclusive first-day offer coming."
- Target: 400 waitlist signups

### Week -1: Final Push
- Daily countdown Stories on Instagram
- "Sneak peek" posts of seller profiles on the app
- Send standees to 5 fish markets for installation
- Press release sent to 20 publications
- Confirm launch-day Instagram Live with 1 food blogger
- Target: 500 waitlist signups

## Launch Week (Day by Day)

### Day 1 (Monday): LAUNCH
- 6 AM: WhatsApp broadcast to all waitlist: "WE'RE LIVE! First 100 orders get free delivery."
- 7 AM: Instagram post + Reel announcing launch
- 8 AM: All ad campaigns go live (Google + Meta + WhatsApp)
- 10 AM: Instagram Live: "Live from Sassoon Dock" with a seller
- 12 PM: Push notification to all app installs
- Target: 50 orders on Day 1

### Day 2 (Tuesday): Social Proof
- Share screenshots of Day 1 orders (with permission)
- "Day 1 sold out Pomfret!" urgency post
- Seller reaction video: "My first Relifish order!"

### Day 3 (Wednesday): Education
- "How to order on Relifish" tutorial Reel
- WhatsApp broadcast: today's catch
- Retargeting ads to Day 1-2 visitors

### Day 4 (Thursday): Press
- Follow up with journalists on press release
- Share any press coverage on social
- "Media is talking about us" Stories

### Day 5 (Friday): Community
- "Fish Friday" special: Rs 50 off all orders
- Instagram poll: "Which fish should we feature next week?"
- UGC repost from early customers

### Day 6-7 (Weekend): Content Blitz
- "Weekend fish feast" messaging
- Recipe Reel: "Make this with your Relifish order"
- Week 1 recap post with metrics

## PR Strategy

### 10 Press Angles
1. "Solo founder vs $810M: How Relifish is taking on FreshToHome with zero inventory"
2. "Mumbai's local fishermen go digital: Inside the app connecting fishers to foodies"
3. "The pre-order revolution: Why this startup lets you reserve tomorrow's catch tonight"
4. "Zero commission for fishermen: How Relifish empowers India's 25M fishing families"
5. "From Sassoon Dock to your doorstep: The tech startup preserving Mumbai's fish culture"
6. "Why this ex-[your background] quit to build a fish marketplace"
7. "WhatsApp-first: The distribution strategy that costs nothing"
8. "India's $22B fish market has zero tech. This startup wants to change that."
9. "The future of India's wet markets: digital, local, personal"
10. "How AI helped build a fish marketplace in weeks" (tech angle)

### Media Targets (20 Publications)
Tier 1 (National): YourStory, Inc42, Economic Times, Mint
Tier 2 (Food/Lifestyle): Conde Nast Traveller India, LBB Mumbai, Curly Tales, Homegrown
Tier 3 (Local Mumbai): Mumbai Mirror, Mid-Day, Hindustan Times Mumbai, DNA
Tier 4 (Tech): TechCrunch India, Entrackr, VCCircle
Tier 5 (Food Industry): Hospitality Biz, Food & Beverage News

## Partnership Strategy

### Restaurant Partnerships (B2B)
- Target: 5 restaurants in Month 2-3
- Pitch: "Fresh, daily delivery direct from fishermen. No middleman markup. Pre-order by 8pm, delivered by 7am."
- Start with: Small independent restaurants near target fish markets
- Revenue potential: Rs 5,000-15,000/order (10-30x consumer orders)

### Food Blogger Ambassador Program
- Select 10 Mumbai food bloggers (5K-50K followers)
- Offer: Free fish for 3 months in exchange for 2 posts/month
- Provide: Branded content kit (photos, copy, hashtags)
- Track: Unique discount codes per blogger

### Housing Society Partnerships
- Approach: 5 large housing societies near fish markets
- Offer: Weekly "Fish Day" at society (seller sets up stall, orders via Relifish)
- WhatsApp group per society for daily catch alerts
- Poster placement in society lifts/notice boards

### Corporate Partnerships
- Target: Office cafeterias, corporate caterers
- Pitch: Weekly fish supply at market rates, pre-ordered and reliable
- Revenue: Recurring B2B revenue stream"""

        add_content(launch_content, story)
    story.append(PageBreak())

    # === CHAPTER 7: PRICING ===
    pricing_text = load_part("pricing")
    if pricing_text:
        story.append(Paragraph("CHAPTER 7: PRICING, UNIT ECONOMICS & FINANCIAL MODEL", styles['ChapterTitle']))
        add_content(pricing_text, story)
    story.append(PageBreak())

    # === CHAPTER 8: CREATIVE ===
    creative_text = load_part("creative")
    if creative_text:
        add_content(creative_text, story)
    story.append(PageBreak())

    # === APPENDIX: IMPLEMENTATION TIMELINE ===
    story.append(Paragraph("APPENDIX: IMPLEMENTATION TIMELINE", styles['ChapterTitle']))

    timeline = """## 12-Month Master Timeline

### Month 1: Validate
- WhatsApp concierge test with 1 seller, 20 buyers
- Fix all website blockers (done: SEO, copy, tracking)
- Launch Instagram account, start content engine
- Google Search Console + Bing submission
- Target: 20 orders, 3 repeat buyers

### Month 2: Launch
- Onboard 5 sellers
- Deploy standees at 2 fish markets
- Run launch week campaign
- Start Google + Meta ads (Rs 30K/month)
- Target: 100 orders, 50 waitlist signups

### Month 3: Grow
- 10+ active sellers
- Area landing pages live (5 areas)
- Food blogger partnerships active (5 bloggers)
- Instagram at 1,000+ followers
- First restaurant partnership
- Target: 200+ monthly orders

### Month 4-6: Scale Mumbai
- 20+ sellers across 3 markets
- Delivery pilot in 2 areas
- Weekly "Fish Day" at 3 housing societies
- Blog content hub with 10+ articles
- SEO traffic starting to compound
- Press coverage (2-3 articles)
- Target: 500+ monthly orders, Rs 2.5L GMV/month

### Month 7-9: Monetize
- Commission collection automated (payment integration)
- B2B channel: 5+ restaurant clients
- Seller subscription tier launched
- Push notifications live
- Target: 1,000+ monthly orders, Rs 5L GMV/month, first revenue

### Month 10-12: Prove & Raise
- 50+ sellers, 2,000+ monthly orders
- Unit economics proven (LTV > 3x CAC)
- Revenue run rate: Rs 3-5L/month
- Seed pitch deck with real numbers
- Target: Rs 1Cr seed round

## Key Metrics Dashboard

North Star: Monthly Gross Merchandise Value (GMV)
Supply: Active sellers, listings per seller, seller retention
Demand: Active buyers, orders per buyer, buyer retention
Marketplace: Liquidity rate (orders/listings), time to first order
Growth: Waitlist signups, CAC, organic vs paid ratio
Revenue: Take rate, revenue per order, monthly revenue

## Budget Summary (6 Months)

Total Pre-Seed Budget: Rs 20-25L
- Founder salary: Rs 6L (Rs 1L/month)
- Paid ads: Rs 3L (Rs 50K/month average)
- Physical marketing: Rs 1.5L (standees, banners, flyers)
- Delivery pilot: Rs 2L (delivery partner costs)
- Tech/hosting: Rs 0.5L (Vercel, Supabase, domain)
- Blogger/influencer: Rs 1L (free fish + small payments)
- Contingency: Rs 6-11L
"""

    add_content(timeline, story)

    # === FINAL PAGE ===
    story.append(PageBreak())
    story.append(Spacer(1, 60*mm))
    story.append(Paragraph("RELIFISH", styles['CoverTitle']))
    story.append(Paragraph("MEGA MARKETING PLAYBOOK", styles['CoverTitle']))
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph("8 Chapters | 15,000+ Words | Every Marketing Lever Covered", styles['CoverSub']))
    story.append(Spacer(1, 5*mm))
    story.append(Paragraph("Brand | Ads | Growth | Content | SEO | Launch | Pricing | Creative", styles['CoverSub']))
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph("relifish.store | April 2026", styles['Small']))
    story.append(Paragraph("Generated by 8 parallel AI marketing agents for Kunal Rawat", styles['Small']))

    doc.build(story)
    print(f"MEGA Playbook PDF saved: {OUT}")

if __name__ == "__main__":
    build_pdf()
